/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackOauthRouteImport } from './routes/callback/oauth'
import { Route as protectedFeedRouteImport } from './routes/(protected)/feed'
import { Route as protectedBrowseRouteImport } from './routes/(protected)/browse'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'
import { Route as protectedCreateBlogIndexRouteImport } from './routes/(protected)/create-blog/index'
import { Route as protectedAdminIndexRouteImport } from './routes/(protected)/admin/index'
import { Route as protectedUsernameIndexRouteImport } from './routes/(protected)/$username/index'
import { Route as ApiMcpSplatRouteImport } from './routes/api/mcp/$'
import { Route as ApiCronSyncLikesRouteImport } from './routes/api/cron/sync-likes'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as protectedEditBlogBlogidRouteImport } from './routes/(protected)/edit-blog/$blogid'
import { Route as protectedAdminDashboardRouteImport } from './routes/(protected)/admin/dashboard'
import { Route as protectedAccountProfileRouteImport } from './routes/(protected)/account/profile'
import { Route as protectedAccountLikedRouteImport } from './routes/(protected)/account/liked'
import { Route as protectedUsernameBlogidRouteImport } from './routes/(protected)/$username/$blogid'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackOauthRoute = CallbackOauthRouteImport.update({
  id: '/callback/oauth',
  path: '/callback/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedFeedRoute = protectedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedBrowseRoute = protectedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedCreateBlogIndexRoute =
  protectedCreateBlogIndexRouteImport.update({
    id: '/create-blog/',
    path: '/create-blog/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedAdminIndexRoute = protectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUsernameIndexRoute = protectedUsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: '/api/mcp/$',
  path: '/api/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncLikesRoute = ApiCronSyncLikesRouteImport.update({
  id: '/api/cron/sync-likes',
  path: '/api/cron/sync-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedEditBlogBlogidRoute = protectedEditBlogBlogidRouteImport.update({
  id: '/edit-blog/$blogid',
  path: '/edit-blog/$blogid',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAdminDashboardRoute = protectedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAccountProfileRoute = protectedAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAccountLikedRoute = protectedAccountLikedRouteImport.update({
  id: '/account/liked',
  path: '/account/liked',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUsernameBlogidRoute = protectedUsernameBlogidRouteImport.update({
  id: '/$username/$blogid',
  path: '/$username/$blogid',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/browse': typeof protectedBrowseRoute
  '/feed': typeof protectedFeedRoute
  '/callback/oauth': typeof CallbackOauthRoute
  '/$username/$blogid': typeof protectedUsernameBlogidRoute
  '/account/liked': typeof protectedAccountLikedRoute
  '/account/profile': typeof protectedAccountProfileRoute
  '/admin/dashboard': typeof protectedAdminDashboardRoute
  '/edit-blog/$blogid': typeof protectedEditBlogBlogidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-likes': typeof ApiCronSyncLikesRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/$username': typeof protectedUsernameIndexRoute
  '/admin': typeof protectedAdminIndexRoute
  '/create-blog': typeof protectedCreateBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/browse': typeof protectedBrowseRoute
  '/feed': typeof protectedFeedRoute
  '/callback/oauth': typeof CallbackOauthRoute
  '/$username/$blogid': typeof protectedUsernameBlogidRoute
  '/account/liked': typeof protectedAccountLikedRoute
  '/account/profile': typeof protectedAccountProfileRoute
  '/admin/dashboard': typeof protectedAdminDashboardRoute
  '/edit-blog/$blogid': typeof protectedEditBlogBlogidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-likes': typeof ApiCronSyncLikesRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/$username': typeof protectedUsernameIndexRoute
  '/admin': typeof protectedAdminIndexRoute
  '/create-blog': typeof protectedCreateBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/browse': typeof protectedBrowseRoute
  '/(protected)/feed': typeof protectedFeedRoute
  '/callback/oauth': typeof CallbackOauthRoute
  '/(protected)/$username/$blogid': typeof protectedUsernameBlogidRoute
  '/(protected)/account/liked': typeof protectedAccountLikedRoute
  '/(protected)/account/profile': typeof protectedAccountProfileRoute
  '/(protected)/admin/dashboard': typeof protectedAdminDashboardRoute
  '/(protected)/edit-blog/$blogid': typeof protectedEditBlogBlogidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-likes': typeof ApiCronSyncLikesRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/(protected)/$username/': typeof protectedUsernameIndexRoute
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/create-blog/': typeof protectedCreateBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/policies'
    | '/forget-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/browse'
    | '/feed'
    | '/callback/oauth'
    | '/$username/$blogid'
    | '/account/liked'
    | '/account/profile'
    | '/admin/dashboard'
    | '/edit-blog/$blogid'
    | '/api/auth/$'
    | '/api/cron/sync-likes'
    | '/api/mcp/$'
    | '/$username'
    | '/admin'
    | '/create-blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/policies'
    | '/forget-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/browse'
    | '/feed'
    | '/callback/oauth'
    | '/$username/$blogid'
    | '/account/liked'
    | '/account/profile'
    | '/admin/dashboard'
    | '/edit-blog/$blogid'
    | '/api/auth/$'
    | '/api/cron/sync-likes'
    | '/api/mcp/$'
    | '/$username'
    | '/admin'
    | '/create-blog'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/about'
    | '/contact'
    | '/policies'
    | '/(auth)/forget-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(protected)/browse'
    | '/(protected)/feed'
    | '/callback/oauth'
    | '/(protected)/$username/$blogid'
    | '/(protected)/account/liked'
    | '/(protected)/account/profile'
    | '/(protected)/admin/dashboard'
    | '/(protected)/edit-blog/$blogid'
    | '/api/auth/$'
    | '/api/cron/sync-likes'
    | '/api/mcp/$'
    | '/(protected)/$username/'
    | '/(protected)/admin/'
    | '/(protected)/create-blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PoliciesRoute: typeof PoliciesRoute
  CallbackOauthRoute: typeof CallbackOauthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncLikesRoute: typeof ApiCronSyncLikesRoute
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/oauth': {
      id: '/callback/oauth'
      path: '/callback/oauth'
      fullPath: '/callback/oauth'
      preLoaderRoute: typeof CallbackOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/feed': {
      id: '/(protected)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof protectedFeedRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/browse': {
      id: '/(protected)/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof protectedBrowseRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/create-blog/': {
      id: '/(protected)/create-blog/'
      path: '/create-blog'
      fullPath: '/create-blog'
      preLoaderRoute: typeof protectedCreateBlogIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/$username/': {
      id: '/(protected)/$username/'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof protectedUsernameIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/api/mcp/$': {
      id: '/api/mcp/$'
      path: '/api/mcp/$'
      fullPath: '/api/mcp/$'
      preLoaderRoute: typeof ApiMcpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-likes': {
      id: '/api/cron/sync-likes'
      path: '/api/cron/sync-likes'
      fullPath: '/api/cron/sync-likes'
      preLoaderRoute: typeof ApiCronSyncLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/edit-blog/$blogid': {
      id: '/(protected)/edit-blog/$blogid'
      path: '/edit-blog/$blogid'
      fullPath: '/edit-blog/$blogid'
      preLoaderRoute: typeof protectedEditBlogBlogidRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/admin/dashboard': {
      id: '/(protected)/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof protectedAdminDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/account/profile': {
      id: '/(protected)/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof protectedAccountProfileRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/account/liked': {
      id: '/(protected)/account/liked'
      path: '/account/liked'
      fullPath: '/account/liked'
      preLoaderRoute: typeof protectedAccountLikedRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/$username/$blogid': {
      id: '/(protected)/$username/$blogid'
      path: '/$username/$blogid'
      fullPath: '/$username/$blogid'
      preLoaderRoute: typeof protectedUsernameBlogidRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgetPasswordRoute: authForgetPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedBrowseRoute: typeof protectedBrowseRoute
  protectedFeedRoute: typeof protectedFeedRoute
  protectedUsernameBlogidRoute: typeof protectedUsernameBlogidRoute
  protectedAccountLikedRoute: typeof protectedAccountLikedRoute
  protectedAccountProfileRoute: typeof protectedAccountProfileRoute
  protectedAdminDashboardRoute: typeof protectedAdminDashboardRoute
  protectedEditBlogBlogidRoute: typeof protectedEditBlogBlogidRoute
  protectedUsernameIndexRoute: typeof protectedUsernameIndexRoute
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
  protectedCreateBlogIndexRoute: typeof protectedCreateBlogIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedBrowseRoute: protectedBrowseRoute,
  protectedFeedRoute: protectedFeedRoute,
  protectedUsernameBlogidRoute: protectedUsernameBlogidRoute,
  protectedAccountLikedRoute: protectedAccountLikedRoute,
  protectedAccountProfileRoute: protectedAccountProfileRoute,
  protectedAdminDashboardRoute: protectedAdminDashboardRoute,
  protectedEditBlogBlogidRoute: protectedEditBlogBlogidRoute,
  protectedUsernameIndexRoute: protectedUsernameIndexRoute,
  protectedAdminIndexRoute: protectedAdminIndexRoute,
  protectedCreateBlogIndexRoute: protectedCreateBlogIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PoliciesRoute: PoliciesRoute,
  CallbackOauthRoute: CallbackOauthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncLikesRoute: ApiCronSyncLikesRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
