const MB = 1024 * 1024;

export const MAX_IMAGE_SIZE = 5 * MB;
export const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/jpg", "image/heic"];

export const BLOG_CATEGORIES = [
  "Agriculture",
  "Architecture",
  "Art",
  "Astronomy",
  "Automotive",
  "Aviation",
  "Beauty",
  "Biotech",
  "Business",
  "Crafts",
  "Culinary",
  "Education",
  "Engineering",
  "Entertainment",
  "Fashion",
  "Finance",
  "Fitness",
  "Gaming",
  "Geology",
  "Health",
  "History",
  "Journalism",
  "Law",
  "Lifestyle",
  "Literature",
  "Meditation",
  "Music",
  "Nature",
  "Parenting",
  "Pets",
  "Photography",
  "Politics",
  "Psychology",
  "Robotics",
  "Science",
  "Spirituality",
  "Sports",
  "Sustainability",
  "Technology",
  "Travel",
  "Volunteering",
] as const;
